"""create profile table

Revision ID: 0e227d1e7fbe
Revises: 
Create Date: 2025-12-30 17:20:39.621077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e227d1e7fbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.CheckConstraint("role IN ('user', 'admin')", name='check_role'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_profiles_username', 'profiles', ['username'], unique=False)
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    # ### end Alembic commands ###
    
    # Adding foreign key constraint to user_id if users table exists
    op.execute("""
        ALTER TABLE profiles 
        ADD CONSTRAINT profiles_user_id_fkey 
        FOREIGN KEY (user_id) 
        REFERENCES auth.users(id) 
        ON DELETE CASCADE
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping foreign key constraint if exists
    op.execute("ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey")
    
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_index('idx_profiles_username', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
