"""create request table

Revision ID: 34d12e2876f1
Revises: ae93cb8fd2d7
Create Date: 2025-12-30 23:50:51.209627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34d12e2876f1'
down_revision: Union[str, Sequence[str], None] = 'ae93cb8fd2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'requests',
        sa.Column('request_id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('request_type', sa.String(length=50), nullable=False),
        sa.Column('request_detail', postgresql.JSONB, nullable=False),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('submitted_by', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('rejected_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('rejected_reason', sa.String(length=50), nullable=True),
        sa.Column('rejection_notes', sa.Text(), nullable=True),
        sa.Column('species_id', sa.String(length=100), nullable=True),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            onupdate=sa.func.current_timestamp(),
            nullable=False
        ),
    )
    op.create_index('idx_requests_status', 'requests', ['status'])
    op.create_index('idx_requests_submitted_by', 'requests', ['submitted_by'])
    op.create_index('idx_requests_updated_at', 'requests', ['updated_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_requests_updated_at', table_name='requests')
    op.drop_index('idx_requests_submitted_by', table_name='requests')
    op.drop_index('idx_requests_status', table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
