"""create collection_item table

Revision ID: ae93cb8fd2d7
Revises: da877f605f29
Create Date: 2025-12-30 23:39:52.566066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae93cb8fd2d7'
down_revision: Union[str, Sequence[str], None] = 'da877f605f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'collection_items',
        sa.Column('item_id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('collection_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('species_id', sa.String(length=100), nullable=False),
        sa.Column(
            'added_at',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            nullable=False
        ),
    )
    
    op.create_index(
        'idx_collection_items_collection',
        'collection_items',
        ['collection_id']
    )

    op.create_index(
        'idx_collection_items_species',
        'collection_items',
        ['species_id']
    )

    op.create_index(
        'uq_collection_species',
        'collection_items',
        ['collection_id', 'species_id'],
        unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_collection_species', table_name='collection_items')
    op.drop_index('idx_collection_items_species', table_name='collection_items')
    op.drop_index('idx_collection_items_collection', table_name='collection_items')
    op.drop_table('collection_items')
    # ### end Alembic commands ###
