"""create news table

Revision ID: cc4fd06544c5
Revises: 0e227d1e7fbe
Create Date: 2025-12-30 22:59:03.939149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cc4fd06544c5'
down_revision: Union[str, Sequence[str], None] = '0e227d1e7fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'news',
        sa.Column('news_id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('news_title', sa.String(length=255), nullable=False),
        sa.Column('news_url', sa.String(length=500), nullable=False),
        sa.Column('news_source', sa.String(length=100), nullable=False),
        sa.Column(
            'published_date',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            nullable=False
        )
    )

    op.create_index(
        'idx_news_published_date',
        'news',
        ['published_date']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_published_date', table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
