"""create favorite table

Revision ID: d12f77823aba
Revises: cc4fd06544c5
Create Date: 2025-12-30 23:18:37.476527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd12f77823aba'
down_revision: Union[str, Sequence[str], None] = 'cc4fd06544c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'favorites',
        sa.Column('favorite_id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('news_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            'added_at',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            nullable=False
        )
    )

    op.create_index(
        'idx_favorite_user_news',
        'favorites',
        ['user_id', 'news_id'],
        unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_favorite_user_news', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
