"""create collection table

Revision ID: da877f605f29
Revises: d12f77823aba
Create Date: 2025-12-30 23:31:48.710616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da877f605f29'
down_revision: Union[str, Sequence[str], None] = 'd12f77823aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'collections',
        sa.Column('collection_id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('collection_name', sa.String(length=100), nullable=False),
        sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            nullable=False
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(),
            server_default=sa.func.current_timestamp(),
            onupdate=sa.func.current_timestamp(),
            nullable=False
        ),
    )

    op.create_index(
        'idx_collections_owner',
        'collections',
        ['owner_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_collections_owner', table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
